# Generated by Django 5.2.4 on 2025-07-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={},
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='application_date',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='status',
        ),
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
        migrations.RemoveField(
            model_name='education',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='education',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='job',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='duration',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='cover_letter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
