# Generated by Django 5.2.4 on 2025-07-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_applicant_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='applicants/cvs/'),
        ),
    ]
