# Generated by Django 5.2.4 on 2025-07-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_applicant_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='cv',
        ),
    ]
