# Generated by Django 4.2.25 on 2025-10-29 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_applicant_cv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Applicant', 'verbose_name_plural': 'Applicants'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-year'], 'verbose_name': 'Education', 'verbose_name_plural': 'Education Records'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-deadline'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['-start_date', '-end_date'], 'verbose_name': 'Work Experience', 'verbose_name_plural': 'Work Experience Records'},
        ),
        migrations.AddField(
            model_name='applicant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='education',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='education',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='honors',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming Languages'), ('framework', 'Frameworks & Libraries'), ('database', 'Databases'), ('cloud', 'Cloud & DevOps'), ('tools', 'Tools & Software'), ('soft', 'Soft Skills'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=2),
        ),
        migrations.AddField(
            model_name='skill',
            name='years_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together={('email', 'position_applied')},
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['email'], name='jobs_applic_email_06b68d_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['status'], name='jobs_applic_status_294c80_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['-created_at'], name='jobs_applic_created_4a1b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['deadline'], name='jobs_job_deadlin_c19edf_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-created_at'], name='jobs_job_created_77460a_idx'),
        ),
    ]
